# Generated by Django 6.0.5 on 2026-05-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_latitude_delivery_expected_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='confirmation_status',
            field=models.CharField(default='Pending', max_length=30),
        ),
        migrations.AddField(
            model_name='delivery',
            name='customer_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='delivery',
            name='rider_requested_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Failed', 'Failed'), ('Waiting Confirmation', 'Waiting Confirmation')], default='Pending', max_length=20),
        ),
    ]
