# Generated by Django 6.0.5 on 2026-05-10 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delivery_confirmation_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='gps_latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='gps_longitude',
            new_name='longitude',
        ),
    ]
